//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aboneler
    {
        public int AboneId { get; set; }
        public string AboneAdi { get; set; }
        public string AboneCinsiyet { get; set; }
        public string AboneTelefon { get; set; }
        public string AboneMail { get; set; }
        public string AbonelikTipi { get; set; }
        public string AbonelikDurumu { get; set; }
        public Nullable<System.DateTime> AbonelikTarihi { get; set; }
    }
}
