//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gorevliler
    {
        public int GorevliId { get; set; }
        public string GorevliAdi { get; set; }
        public string Gorevli_k_adi { get; set; }
        public string Gorevli_sifre { get; set; }
    }
}
