//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KutuphaneProjeEntities : DbContext
    {
        public KutuphaneProjeEntities()
            : base("name=KutuphaneProjeEntities")
        {

        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aboneler> Aboneler { get; set; }
        public virtual DbSet<Gorevliler> Gorevliler { get; set; }
        public virtual DbSet<Kitaplar> Kitaplar { get; set; }
        public virtual DbSet<Turler> Turler { get; set; }
        public virtual DbSet<YayinEvleri> YayinEvleri { get; set; }
        public virtual DbSet<Yazarlar> Yazarlar { get; set; }
    }
}
